#!/usr/bin/env bash
# Put the GitHub / Google sign-in credentials on the server and turn the buttons on.
#
#   ./setup-oauth-login.sh
#
# It prompts, writes them straight into the server's .env over ssh, restarts the backend
# and checks that the gateway now reports the provider as available.
#
# The secrets are read with the terminal echo off, are never written to a local file, and
# travel to the remote shell on stdin rather than as command arguments — an argument would
# be visible to anyone running `ps` on the server for as long as the command ran.
#
# Safe to re-run: it replaces the four keys in place and leaves everything else in .env
# alone, keeping a timestamped backup each time. deploy.sh excludes .env from its rsync,
# so a later deploy will not overwrite any of this.
#
# Before running, register the two OAuth apps and have their credentials to hand. The
# callback URLs have to match exactly:
#
#   GitHub  https://github.com/settings/developers → New OAuth App
#           Homepage URL              https://code.mrday.one
#           Authorization callback URL
#               https://code.mrday.one/api/auth/oauth/github/callback
#
#   Google  https://console.cloud.google.com/apis/credentials
#           → Create credentials → OAuth client ID → Web application
#           Authorised redirect URI
#               https://code.mrday.one/api/auth/oauth/google/callback
#           The consent screen needs the email and profile scopes, and while it is in
#           "Testing" only the accounts listed as test users can sign in — publish it
#           when you want it open to everyone.
set -euo pipefail

SERVER_HOST="${SERVER_HOST:-154.44.13.133}"
SERVER_USER="${SERVER_USER:-root}"
SERVER_KEY="${SERVER_KEY:-$HOME/.ssh/michael_server}"
REMOTE_DIR="${REMOTE_DIR:-/opt/michael-ide-deploy/server}"
PUBLIC_BASE="${PUBLIC_BASE:-https://code.mrday.one}"
REMOTE="${SERVER_USER}@${SERVER_HOST}"

# This host drops a large share of ssh handshakes ("banner exchange: invalid format"), so
# every remote call is retried rather than failing the run.
ssh_stdin() {
  local attempt payload
  payload="$(cat)"
  for attempt in 1 2 3 4 5; do
    if printf '%s' "$payload" \
      | ssh -i "$SERVER_KEY" -o BatchMode=yes -o ConnectTimeout=25 "$REMOTE" 'bash -s'; then
      return 0
    fi
    echo "    (attempt $attempt failed, retrying in $((attempt * 3))s)" >&2
    sleep $((attempt * 3))
  done
  return 1
}

ask() {                      # ask VAR "Prompt" secret|plain
  local __var="$1" __prompt="$2" __mode="$3" __value=""
  if [ "$__mode" = "secret" ]; then
    read -rs -p "  $__prompt: " __value
    echo
  else
    read -r -p "  $__prompt: " __value
  fi
  printf -v "$__var" '%s' "$__value"
}

# Single quotes are what protects the value inside the remote .env line, so a value
# containing one has to close, escape and reopen the quoting. Secrets are generated by the
# providers and will not contain one — but a config file that silently corrupts on an
# unexpected character is not worth the saved line.
shell_quote() {
  printf "'%s'" "${1//\'/\'\\\'\'}"
}

echo
echo "Sign-in providers for $PUBLIC_BASE"
echo "Leave both fields of a provider empty to skip it and leave its button off."
echo

echo "GitHub — callback $PUBLIC_BASE/api/auth/oauth/github/callback"
ask GH_ID     "Client ID    " plain
ask GH_SECRET "Client secret" secret
echo
echo "Google — callback $PUBLIC_BASE/api/auth/oauth/google/callback"
ask GG_ID     "Client ID    " plain
ask GG_SECRET "Client secret" secret
echo

# Catch the mistakes that otherwise only surface as a provider error page after someone
# has already approved: a half-filled provider, or an id pasted into the wrong prompt.
fail() { echo "  $1" >&2; exit 1; }
if { [ -n "$GH_ID" ] && [ -z "$GH_SECRET" ]; } || { [ -z "$GH_ID" ] && [ -n "$GH_SECRET" ]; }; then
  fail "GitHub needs both an id and a secret, or neither."
fi
if { [ -n "$GG_ID" ] && [ -z "$GG_SECRET" ]; } || { [ -z "$GG_ID" ] && [ -n "$GG_SECRET" ]; }; then
  fail "Google needs both an id and a secret, or neither."
fi
if [ -z "$GH_ID" ] && [ -z "$GG_ID" ]; then
  fail "Nothing to do — both providers were left empty."
fi
case "$GG_ID" in
  ""|*.apps.googleusercontent.com) ;;
  *) fail "That does not look like a Google client ID (they end in .apps.googleusercontent.com)." ;;
esac
case "$GH_ID" in
  *.apps.googleusercontent.com) fail "That is the Google client ID — it went into the GitHub prompt." ;;
esac

echo "==> writing to $REMOTE:$REMOTE_DIR/.env"
{
  echo "set -euo pipefail"
  echo "cd $(shell_quote "$REMOTE_DIR")"
  echo 'cp -a .env ".env.bak.$(date +%Y%m%d-%H%M%S)"'
  echo 'set_key() {'
  # The value arrives on this function's stdin for the same reason as above: as an
  # argument it would be visible in `ps` while the write ran.
  echo '  local key="$1" value; value="$(cat)"'
  echo '  if grep -qE "^${key}=" .env; then'
  echo '    grep -vE "^${key}=" .env > .env.tmp'
  echo '  else'
  echo '    cp .env .env.tmp'
  echo '  fi'
  echo '  printf "%s=%s\n" "$key" "$value" >> .env.tmp'
  echo '  mv .env.tmp .env'
  echo '}'
  echo 'chmod 600 .env'
  if [ -n "$GH_ID" ]; then
    echo "set_key GITHUB_LOGIN_CLIENT_ID <<'MDO_EOF'"
    echo "$GH_ID"
    echo "MDO_EOF"
    echo "set_key GITHUB_LOGIN_CLIENT_SECRET <<'MDO_EOF'"
    echo "$GH_SECRET"
    echo "MDO_EOF"
  fi
  if [ -n "$GG_ID" ]; then
    echo "set_key GOOGLE_CLIENT_ID <<'MDO_EOF'"
    echo "$GG_ID"
    echo "MDO_EOF"
    echo "set_key GOOGLE_CLIENT_SECRET <<'MDO_EOF'"
    echo "$GG_SECRET"
    echo "MDO_EOF"
  fi
  echo 'echo "  .env updated"'
  # --force-recreate because compose only re-reads .env when the container is replaced;
  # a plain `up -d` sees no change to the image and leaves the old environment running.
  echo 'echo "==> restarting the gateway"'
  # stdout is noise; stderr is kept, because a failed recreate is the one thing worth
  # seeing here and `set -e` stops before the health check below would report it.
  echo 'docker compose -p server up -d --force-recreate backend >/dev/null'
  echo 'for i in $(seq 1 30); do'
  echo '  if curl -fsS http://127.0.0.1:8080/health >/dev/null 2>&1; then echo "  gateway healthy"; exit 0; fi'
  echo '  sleep 2'
  echo 'done'
  echo 'echo "  gateway did not come back healthy — check: docker compose -p server logs --tail=50 backend" >&2'
  echo 'exit 1'
} | ssh_stdin

echo "==> checking what the sign-in page will now be offered"
for attempt in 1 2 3 4 5; do
  answer="$(curl -fsS --max-time 20 "$PUBLIC_BASE/api/auth/oauth/providers" 2>/dev/null || true)"
  [ -n "$answer" ] && break
  sleep 3
done
echo "  $PUBLIC_BASE/api/auth/oauth/providers -> ${answer:-no answer}"
echo
case "$answer" in
  *'"github":true'*|*'"google":true'*)
    echo "Done. Open $PUBLIC_BASE/gate — the enabled buttons no longer say Soon."
    echo "If a sign-in fails, the page shows the reason and the detail is in:"
    echo "  ssh -i $SERVER_KEY $REMOTE 'docker compose -p server logs --tail=50 backend'"
    ;;
  *)
    echo "The gateway still reports both providers as off. The usual cause is a value"
    echo "that did not land — re-run this script, or check the keys are present with:"
    echo "  ssh -i $SERVER_KEY $REMOTE 'grep -c GITHUB_LOGIN_CLIENT_ID $REMOTE_DIR/.env'"
    ;;
esac
